#!/bin/bash

# source directories
LINUX=linux
TARGET_LINUX=target/linux
BUSYBOX=busybox


# setting up linux source tree

if [ ! -d $LINUX ]
then
	read -p "Linux source doesn't exist, git clone it from kernel.org? [y/N] " REPLY

	case $REPLY in
		y | Y)
			git clone git@github.com:hominlinx/linux-bananapi.git $LINUX
			;;
		*)
			echo "So, please prepare linux source(in a directory named $LINUX) by yourself."
			exit 1
			;;
	esac
fi

#创建target/linux , 目的是将这些生成物放到target/linux下。
if [ ! -d  $TARGET_LINUX ]
then
	read -p "Linux target doesn't exist, mkdir it? [y/N]" REPLY
	case $REPLY in
		y | Y)
			mkdir -p $TARGET_LINUX
			;;
		*)
			echo "dump..."
			exit 1
			;;
	esac
fi

#将config cp到目标位置
#make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOADADDR=0x48000000  INSTALL_MOD_PATH=./_install O=../$TARGET_LINUX -C $LINUX sun4i_defconfig
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOADADDR=0x48000000  INSTALL_MOD_PATH=./_install O=../$TARGET_LINUX -C $LINUX  vexpress_defconfig 


# setting up busybox source tree

if [ ! -d $BUSYBOX ]
then
	read -p "Busybox source doesn't exist, git clone it from busybox.net? [y/N] " REPLY

	case $REPLY in
		y | Y)
			git clone git://git.busybox.net/busybox $BUSYBOX
			;;
		*)
			echo "So, please prepare busybox source(in a directory named $BUSYBOX) by yourself."
			exit 1
			;;
	esac
fi

make CROSS_COMPILE=arm-linux-gnueabihf- -C $BUSYBOX defconfig
#make -C $BUSYBOX defconfig
