#!/bin/bash

#制作根文件系统，思路：先在Ubuntu主机环境下，形成目录结构，里面存放的文件和目录与单板上运行所需要的目录结构完全一样，然后再打包成镜像（在开发板看来就是SD卡），这个临时的目录结构称为根目录



CWD=$(pwd)
BUSYBOX=busybox

[ "$#" = "1"  ] || { echo "Usage: $(basename "$0") filename_of_image"; exit 1;  }

#创建rootfs目录（根目录），根文件系统内的文件全部放到这里
sudo rm -rf rootfs
sudo mkdir rootfs


sudo cp -rf ${CWD}/${BUSYBOX}/_install/* rootfs/

sudo mkdir -p rootfs/dev
sudo mkdir -p rootfs/proc
sudo mkdir -p rootfs/sys
sudo mkdir -p rootfs/lib
sudo mkdir -p rootfs/tmp
#创建4个tty端终设备
sudo mknod rootfs/dev/tty1 c 4 1

sudo mknod rootfs/dev/tty2 c 4 2

sudo mknod rootfs/dev/tty3 c 4 3

sudo mknod rootfs/dev/tty4 c 4 4

sudo cp -P /usr/arm-linux-gnueabihf/lib/* rootfs/lib/


dd if=/dev/zero of=a9rootfs.ext3 bs=1M count=100

mkfs.ext3 a9rootfs.ext3
sudo mkdir tmpfs
sudo mount -t ext3 a9rootfs.ext3 tmpfs/ -o loop
sudo cp -r rootfs/*  tmpfs/
sudo umount tmpfs
cp a9rootfs.ext3 ${CWD}/${1}

exit 0
